name: Build
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          # fetch-depth: 0
        # with:
          # fetch-depth: 0
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
     